import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { trpc } from "@/lib/trpc";
import { Loader2, Calendar, Clock, Video } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { format } from "date-fns";
export function ParentSchedule({ studentId, studentName }) {
    const { data: sessions, isLoading } = trpc.parent.getUpcomingSessions.useQuery({ studentId });
    if (isLoading) {
        return (_jsx("div", { className: "flex items-center justify-center py-12", children: _jsx(Loader2, { className: "animate-spin w-8 h-8 text-blue-700" }) }));
    }
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-bold text-gray-900", children: "Schedule & Sessions" }), _jsxs("p", { className: "text-gray-600 mt-1", children: ["Upcoming Zoom sessions for ", studentName] })] }), sessions && sessions.length > 0 ? (_jsx("div", { className: "space-y-4", children: sessions.map((session) => (_jsx(Card, { className: "hover:shadow-lg transition-shadow", children: _jsx(CardContent, { className: "pt-6", children: _jsxs("div", { className: "flex items-start gap-4", children: [_jsx("div", { className: "flex-shrink-0", children: _jsx("div", { className: "w-16 h-16 rounded-lg bg-blue-100 flex items-center justify-center", children: _jsx(Video, { className: "w-8 h-8 text-blue-700" }) }) }), _jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex items-start justify-between mb-2", children: [_jsxs("h3", { className: "font-semibold text-gray-900", children: ["Session #", session.sessionNumber] }), _jsx(Badge, { className: "bg-blue-500", children: "Scheduled" })] }), _jsxs("div", { className: "space-y-2 text-sm text-gray-600", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Calendar, { className: "w-4 h-4" }), _jsx("span", { children: format(new Date(session.scheduledAt), "PPPP 'at' p") })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Clock, { className: "w-4 h-4" }), _jsxs("span", { children: [session.duration, " minutes"] })] })] }), session.zoomLink && (_jsx("div", { className: "mt-4", children: _jsxs("a", { href: session.zoomLink, target: "_blank", rel: "noopener noreferrer", className: "inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors text-sm", children: [_jsx(Video, { className: "w-4 h-4" }), "Join Zoom Session"] }) }))] })] }) }) }, session.id))) })) : (_jsx(Card, { children: _jsx(CardContent, { className: "py-12", children: _jsxs("div", { className: "text-center", children: [_jsx(Calendar, { className: "w-16 h-16 text-gray-300 mx-auto mb-4" }), _jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-2", children: "No Upcoming Sessions" }), _jsx("p", { className: "text-gray-600", children: "New sessions will appear here when scheduled by the teacher." })] }) }) }))] }));
}
