import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Download, FileText, CheckCircle } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
export function LessonCertificates({ certificates, isLoading }) {
    if (isLoading) {
        return (_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsxs(CardTitle, { className: "flex items-center gap-2", children: [_jsx(FileText, { className: "w-5 h-5 text-blue-600" }), "My Certificates"] }) }), _jsx(CardContent, { children: _jsx("div", { className: "text-center py-8 text-gray-500", children: "Loading certificates..." }) })] }));
    }
    return (_jsxs(Card, { children: [_jsxs(CardHeader, { children: [_jsxs(CardTitle, { className: "flex items-center gap-2", children: [_jsx(FileText, { className: "w-5 h-5 text-blue-600" }), "My Certificates"] }), _jsxs(CardDescription, { children: [certificates.length, " certificates earned"] })] }), _jsx(CardContent, { children: certificates.length === 0 ? (_jsxs("div", { className: "text-center py-8 text-gray-500", children: [_jsx(CheckCircle, { className: "w-12 h-12 mx-auto mb-4 opacity-50" }), _jsx("p", { children: "Complete all 3 difficulty levels to earn a certificate!" })] })) : (_jsx("div", { className: "space-y-3", children: certificates.map((cert) => (_jsxs("div", { className: "flex items-center justify-between p-4 rounded-lg bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-200", children: [_jsxs("div", { className: "flex-1", children: [_jsx("h3", { className: "font-semibold text-gray-900", children: cert.lesson.title }), _jsxs("p", { className: "text-sm text-gray-600", children: ["Completed on ", new Date(cert.completedAt).toLocaleDateString()] })] }), _jsxs(Button, { variant: "outline", size: "sm", className: "ml-4", onClick: () => window.open(cert.certificateUrl, "_blank"), children: [_jsx(Download, { className: "w-4 h-4 mr-2" }), "Download"] })] }, cert.id))) })) })] }));
}
