import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { trpc } from "@/lib/trpc";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Calendar, Clock, Video, Users } from "lucide-react";
import { format, addDays, startOfWeek } from "date-fns";
export default function TeacherSchedule() {
    const { data: sessions, isLoading } = trpc.teacher.getUpcomingSessions.useQuery();
    if (isLoading) {
        return (_jsx("div", { className: "flex items-center justify-center h-64", children: _jsx("div", { className: "animate-spin w-8 h-8 border-4 border-blue-600 border-t-transparent rounded-full" }) }));
    }
    const today = new Date();
    const weekStart = startOfWeek(today, { weekStartsOn: 1 }); // Monday
    const weekDays = Array.from({ length: 7 }, (_, i) => addDays(weekStart, i));
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-2xl font-bold text-gray-900", children: "Session Schedule" }), _jsx("p", { className: "text-gray-600 mt-1", children: "Manage your Zoom sessions with Elite students" })] }), _jsx(Button, { className: "bg-blue-600 hover:bg-blue-700", children: "Set Availability" })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsx(CardTitle, { children: "This Week's Sessions" }), _jsxs("div", { className: "flex items-center gap-2 text-sm text-gray-600", children: [_jsx(Calendar, { className: "w-4 h-4" }), _jsxs("span", { children: [format(weekStart, "MMM d"), " - ", format(addDays(weekStart, 6), "MMM d, yyyy")] })] })] }) }), _jsx(CardContent, { children: _jsx("div", { className: "grid grid-cols-7 gap-2", children: weekDays.map((day, index) => {
                                const isToday = format(day, "yyyy-MM-dd") === format(today, "yyyy-MM-dd");
                                const daySessions = sessions?.filter((s) => format(new Date(s.scheduledAt), "yyyy-MM-dd") === format(day, "yyyy-MM-dd")) || [];
                                return (_jsxs("div", { className: `p-3 rounded-lg border ${isToday ? "bg-blue-50 border-blue-300" : "bg-white border-gray-200"}`, children: [_jsxs("div", { className: "text-center mb-2", children: [_jsx("p", { className: "text-xs font-medium text-gray-600", children: format(day, "EEE") }), _jsx("p", { className: `text-lg font-bold ${isToday ? "text-blue-600" : "text-gray-900"}`, children: format(day, "d") })] }), _jsx("div", { className: "space-y-1", children: daySessions.map((session) => (_jsx("div", { className: "text-xs p-1 bg-blue-100 rounded text-blue-900 truncate", title: `${session.studentName} - ${format(new Date(session.scheduledAt), "h:mm a")}`, children: format(new Date(session.scheduledAt), "h:mm a") }, session.id))) })] }, index));
                            }) }) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Upcoming Sessions" }) }), _jsx(CardContent, { children: !sessions || sessions.length === 0 ? (_jsxs("div", { className: "text-center py-8 text-gray-500", children: [_jsx(Calendar, { className: "w-12 h-12 mx-auto mb-3 text-gray-300" }), _jsx("p", { children: "No upcoming sessions scheduled" }), _jsx("p", { className: "text-sm mt-1", children: "Sessions will appear here once students book them" })] })) : (_jsx("div", { className: "space-y-3", children: sessions.slice(0, 10).map((session) => (_jsxs("div", { className: "flex items-center justify-between p-4 bg-gray-50 rounded-lg border border-gray-200 hover:shadow-md transition-shadow", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-blue-100 flex items-center justify-center text-blue-700 font-semibold", children: session.studentName?.charAt(0).toUpperCase() }), _jsxs("div", { children: [_jsx("p", { className: "font-semibold text-gray-900", children: session.studentName }), _jsxs("div", { className: "flex items-center gap-3 text-sm text-gray-600 mt-1", children: [_jsxs("span", { className: "flex items-center gap-1", children: [_jsx(Calendar, { className: "w-3 h-3" }), format(new Date(session.scheduledAt), "MMM d, yyyy")] }), _jsxs("span", { className: "flex items-center gap-1", children: [_jsx(Clock, { className: "w-3 h-3" }), format(new Date(session.scheduledAt), "h:mm a")] }), _jsxs("span", { className: "flex items-center gap-1", children: [_jsx(Users, { className: "w-3 h-3" }), "Session #", session.sessionNumber] })] })] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsxs("span", { className: "text-sm text-gray-600", children: [session.duration, " min"] }), _jsxs(Button, { size: "sm", className: "bg-blue-600 hover:bg-blue-700", children: [_jsx(Video, { className: "w-4 h-4 mr-1" }), "Join"] })] })] }, session.id))) })) })] }), _jsxs(Card, { className: "bg-gradient-to-r from-blue-50 to-indigo-50 border-blue-200", children: [_jsx(CardHeader, { children: _jsx(CardTitle, { className: "text-blue-900", children: "Availability Management" }) }), _jsxs(CardContent, { className: "space-y-2 text-sm text-blue-800", children: [_jsx("p", { children: "\u2022 Set your weekly availability to allow students to book sessions" }), _jsx("p", { children: "\u2022 Each Elite student requires 2 sessions per week" }), _jsx("p", { children: "\u2022 Sessions are 60 minutes each" }), _jsx("p", { children: "\u2022 Students can book sessions within your available time slots" }), _jsx("p", { children: "\u2022 You'll receive notifications 24 hours before each session" })] })] })] }));
}
